name: CI

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true
    env:
      VYBE_VERSION_SUFFIX: win-x64

    steps:
      - uses: actions/checkout@v4
        with:
         ref: ${{ github.head_ref }}   # checkout the correct branch name
         fetch-depth: 0                # fetch the whole repo history
         set-safe-directory: false

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: build
        env:
          VYBE_RESOURCE_FOLDER: native
        run: |
          clj -M:win -m vybe.native.loader
          clojure -T:build uber
          dir native

      - name: package
        run: |
          jpackage --java-options '--enable-native-access=ALL-UNNAMED' --java-options '-Djava.library.path=native' --app-content native --type msi --win-dir-chooser --win-menu --win-console -i target -n leo --main-class leo.main --main-jar leo-0.1.0-standalone.jar
          dir

      - name: upload package
        uses: actions/upload-artifact@v4
        with:
           name: leo-win
           path: leo-1.0.msi
           if-no-files-found: error
           retention-days: 30
           compression-level: 6
           overwrite: true

  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true
    env:
      VYBE_VERSION_SUFFIX: linux-x64

    steps:
      - uses: actions/checkout@v4
        with:
         ref: ${{ github.head_ref }}   # checkout the correct branch name
         fetch-depth: 0                # fetch the whole repo history

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: build
        run: |
          clojure -T:build uber

      - name: package
        run: |
          rm -rf target/classes && jpackage --java-options '--enable-native-access=ALL-UNNAMED' -i target -n leo --main-class leo.main --main-jar leo-0.1.0-standalone.jar
          ls

      - name: upload package
        uses: actions/upload-artifact@v4
        with:
           name: leo-linux
           path: leo_1.0_amd64.deb
           if-no-files-found: error
           retention-days: 30
           compression-level: 6
           overwrite: true

  build-macos:
    runs-on: macOS-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
        with:
         ref: ${{ github.head_ref }}   # checkout the correct branch name
         fetch-depth: 0                # fetch the whole repo history

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: build
        run: |
          clojure -T:build uber

      - name: package
        run: |
          rm -rf target/classes && jpackage --java-options '-XstartOnFirstThread' --java-options '--enable-native-access=ALL-UNNAMED' -i target -n leo --main-class leo.main --main-jar leo-0.1.0-standalone.jar
          ls

      - name: upload package
        uses: actions/upload-artifact@v4
        with:
           name: leo-osx
           path: leo-1.0.dmg
           if-no-files-found: error
           retention-days: 30
           compression-level: 6
           overwrite: true
